### ISSUE TITLE
Multiple scala dependencies

### ISSUE THREAD

**Issue by fommil** [mpeltonen/sbt-idea#179]
I am taking the Coursera course on Scala and – when running this on the sbt sources that come with the course – the IDEA project definitions have multiple versions of Scala as dependency. Notably:
- org.scala-lang_scala-library_2.9.2
- scala-2.9.2
- scala-2.9.1

I think this is a bug with sbt-idea, it should be easy for you to reproduce.

(In this particular project example, there are 3 modules and one must remove all but the "assignment" modules before being able to remove the redundant libraries.)

**Comment by mpeltonen** [comment]
For the coursera assignments, the sbt.version is set to 0.11.3 for all but the last assignment, so I'd guess that scala-2.9.1 comes because of sbt 0.11?  It is used only in assignment-build -module, i.e. the project build module, because sbt 0.11.3 uses scala 2.9.1 and requires that.

So with current information I'd say this is as it should be. Is this causing you some trouble?

**Comment by fommil** [comment]
OK, that's a good explanation. I basically only wanted to import the assignment part – the other bits are just framework for submission that I only use from the command line.

Having multiple scalas was causing a problem in source code lookup – I'd sometimes expand the wrong jar by accident, or I wouldn't be certain which version I was looking at.
