### ISSUE TITLE
too many modules and libraries

### ISSUE THREAD

**Issue by fommil** [mpeltonen/sbt-idea#180]
When I run gen-idea on fairly simple projects, I get two modules created:
- default-{6-digit-hex}
- default-{6-digit-hex}-build

The latter seems to have nothing to do with my project, so I have to delete it.

Also, even though I am explicitly using scala-2.10.0-RC1, scala-2.9.2 is imported as well, which I also have to delete. There is also the scala-lang library for 2.10.0-RC1. I delete the 2.9.2 every time.

It would be really nice if:
1. "-build" module wasn't created.
2. scala-2.9.2 wasn't added as a dependency. 
3. The imported project name matched the name in build.sbt.

**Comment by mpeltonen** [comment]
1) & 2) is because currently the module for sbt build definition is always created and there's no way to disable its generation. We should add a setting (which actually existed in sbt 0.7 -version of the plugin) or command line argument to allow disabling its generation.

3) has been discussed in #136. See also this: https://github.com/harrah/xsbt/issues/554#issuecomment-9175691

You can get the name you want by using the full configuration (*.scala -files instead of .sbt), but that's of course not a really good option for builds that don't otherwise need the full definition power.

**Comment by mpeltonen** [comment]
I just added command line option 'no-sbt-build-module' to latest snapshot (sbt 0.12 version only for now). So 'gen-idea no-sbt-build-module' command should now fix number 1. & 2.

For the 3., the project name is now used as Idea module name if the project is single-module. This should probably fix most of the cases, because build.sbt is mostly used in single module builds, and for single-module projects using name here should be just fine.

Try the latest snapshot if it works better for your projects.

**Comment by fommil** [comment]
Hmm, I'm using

```
resolvers += "Sonatype snapshots" at "http://oss.sonatype.org/content/repositories/snapshots/"
addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.2.0-SNAPSHOT")
```

in `~/.sbt/plugins/plugins.sbt` but (even after a `project` dir clean out) the following happens

```
$ sbt gen-idea no-sbt-build-module
[info] Loading global plugins from ~/.sbt/plugins
...
[error] Not a valid command: no-sbt-build-module
[error] Expected '/'
[error] Expected ':'
[error] Not a valid key: no-sbt-build-module
[error] no-sbt-build-module
[error]                    ^

```

**Comment by fommil** [comment]
Sorry, I had a local project cache that wasn't being updated – also when I ran this in the console it worked :-)

**Comment by fommil** [comment]
This looks _much_ better – how can I make it the default?

One small thing though: Scala 2.9.2 is still being pulled in (as well as my Scala-2.10-RC2). How can I get rid of that?

**Comment by mpeltonen** [comment]
Yeah, the scala-2.9.2 lib seems to get included anyway. I'll check if that could be eliminated in this case.

You can make it default by using aliases. Add this to ~/.sbtrc

``` code
alias gen-idea=gen-idea no-sbt-build-module
```

(You can of course use also some other alias as gen-idea if you like)

**Comment by larvanitis** [comment]
Thank you for the fix!
I came here looking for exactly that and I found it:)

@fommil when you run commands outside sbt (eg. linux shell), you have to enclose each sbt command with its arguments in double-quotes like `sbt "gen-idea no-sbt-build-module"` otherwise it will parse the argument(s) as separate command(s) thus throwing an `[error] Not a valid command`
