### ISSUE TITLE
sbt scala version added

### ISSUE THREAD

**Issue by fommil** [mpeltonen/sbt-idea#210]
even if my scala version in build.sbt is set to 2.10.1, the 2.9.2 is still added to the IntelliJ library list.

This is a minor inconvenience as I always remove it in order to be sure that the IntelliJ indexing doesn't bloat up.

IntelliJ always complains that the Scala jar is not used anyway, but it is referenced by the compiler so it has to remain.

**Comment by mpeltonen** [comment]
Yeah, it is there for the sbt build definition module, which requires it because sbt uses Scala 2.9.2. 

If you do "gen-idea no-sbt-build-module", then it is not referenced by any project. Library is still generated though.

I've noticed too that IntelliJ complains about the scala jar not used, even if compiler references it!
