### ISSUE TITLE
Align IDEA and SBT output paths

### ISSUE THREAD

**Issue by hseeberger** [mpeltonen/sbt-idea#5]
SBT uses target/... as output paths. The defaults in IDEA are different, e.g. out/production/...
The plugin should change the IDEA settings for the project to point to target and the modules to point to <module>/target/<scala-version>/classes and  <module>/target/<scala-version>/test-classes

**Comment by ijuma** [comment]
There's a suggested fix for that here http://github.com/ijuma/sbt-idea-plugin/commit/c73d9b8e09a02fecfa86906196af2691ada2e451

**Comment by mpeltonen** [comment]
Merged, thx!

**Comment by mtkopone** [comment]
Hi, 
Is there a way to disable this feature? 

At least for me this is not the desired behavior. There's a reason that sbt and idea build to different directories, since both of them have separate mechanisms for detecting what needs to be built and when. Also, I frequently both run our application in idea and run tests with e.g. test-quick in sbt. Now they just end up confusing each other.

**Comment by mpeltonen** [comment]
Currently there's no way, but I agree that this would be a good candidate for being configurable. It's also easy to implement. Will do.

**Comment by ijuma** [comment]
I agree that making this configurable is good. Having said that, there is no reason why IDEA and sbt have to confuse each other. All you have to do is configure IDEA not to run make when tests and applications are launched. Then you can run things from IDEA or sbt and the results are the same.

**Comment by sirthias** [comment]
Actually in order to _really_ align the IDEA and SBT output paths you also need to tell IDEA to also put the target/2.8.0/resources directory on the classpath (target/2.8.0/test-resources for tests). Otherwise your application (or tests) will not find any resources while on the SBT side they will.
Check this post for how to achieve that:
http://www.decodified.com/scala/2010/10/12/an-integrated-sbt-and-idea-scala-dev-setup.html

**Comment by ijuma** [comment]
sirthias,

The plugin has done that for a while:

http://github.com/mpeltonen/sbt-idea-plugin/issues/closed#issue/8

Ismael

**Comment by sirthias** [comment]
Well, actually it's not quite right, that IDEA only supports output directories. The resource directories do not need to be modeled as dependencies. You _can_ put a path of directories (separated by ':' on Unixes, ';' under Windows) into the "output directory" field. This saves you from setting up extra dependencies.

Cheers,
Mathias

**Comment by ijuma** [comment]
Thanks, that's useful to know. Is this documented somewhere or is it an implementation artifact? Also, is there any behaviour difference that way?

**Comment by sirthias** [comment]
I'm not sure this is an official feature, therefore I'm guessing it's what you call an "implementation artifact". Since you already implemented another working solution I probably wouldn't change anything about it. Consider my comment rather as an "nice to know" addition...

**Comment by ijuma** [comment]
Makes sense. Thanks!
